### ISSUE TITLE
.row class bug

### ISSUE THREAD

**Issue by coryrylan** [coryrylan/core-grid#12]
change the `overflow: hidden` to `overflow: visible`.
This fixes hidden element issues with pop ups, datepickers and dropdowns. 

``` scss
.row {
    margin-left: -8px;
    margin-right: -8px;

    &:before, &:after {
        content: " ";
        display: table;
        width: 0;
    }

    &:after {
        clear: both;
    }
}
```
